### ISSUE TITLE
BindBC

### ISSUE THREAD

**Issue by ichordev** [GoaLitiuM/bindbc-bgfx#6]
Would you be interested in making bindbc-bgfx an official BindBC package? The only thing is that I would need to transfer the repository to BindBC/bindbc-bgfx, and then you would need to transfer ownership of the dub package to me.
If you think that's not for you, then perhaps we'd still be able to negotiate some way for me to publish an official BindBC bgfx package using the "bindbc-bgfx" name in the dub registry.

**Comment by GoaLitiuM** [comment]
Sure. I have not had any time to work in D for some time, so maybe it would be better to also let someone else maintain the repository.

**Comment by ichordev** [comment]
> Sure. I have not had any time to work in D for some time, so maybe it would be better to also let someone else maintain the repository.

That's great to hear!
If you can transfer the dub package to me then I'll handle migrating the repository. According to this page on the dub package repository, to transfer a project you're meant to [open an issue in dlang/dub-registry](https://github.com/dlang/dub-registry/issues):
![image](https://user-images.githubusercontent.com/15670465/208250391-0db5e327-3d10-4ebe-9c22-bf76015ad503.png)
I think it tends to take a little while, but if the transfer request has insufficient information it tends to get no response. Just make sure to specify your dub username, and that my dub username is `ichordev`. Good luck. :)

**Comment by ichordev** [comment]
Just confirming that the transfer has worked. I'm currently quite busy with updating bindbc-sdl & testing that it still works, but I'll copy bindbc-bgfx to the BindBC repo soon and I'll be working on it from there. Thanks for your help! :+1:
